.PHONY: run-update-all create-network

SHELL := /bin/sh

run-update-all:
	@if [ -f .env ]; then . ./.env; fi ; \
	EXCLUDE="$${EXCLUDE}" ; \
	echo "Exclusions: $${EXCLUDE:-<none>}" ; \
	for dir in */; do \
		name=$${dir%/} ; \
		skip=0 ; \
		for e in $$EXCLUDE; do \
			if [ "$$name" = "$$e" ]; then \
				skip=1 ; break ; \
			fi ; \
		done ; \
		if [ $$skip -eq 1 ]; then \
			echo "Skipping $$dir" ; \
			continue ; \
		fi ; \
		if [ -f "$$dir/Makefile" ]; then \
			$(MAKE) -C "$$dir" update-run ; \
		fi ; \
	done

create-network:
	docker network create home-lab-net || true