# Start from the official Jenkins SSH agent image
FROM jenkins/ssh-agent:latest

# Define the docker group id passed as parameter
ARG DOCKER_GID

# Switch to root to install packages
USER root

# Install dependencies for Docker installation
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    make

# Add Docker's official GPG key
RUN install -m 0755 -d /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc && \
    chmod a+r /etc/apt/keyrings/docker.asc

# Add Docker's repository to Apt sources
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null

# Update and install only the Docker CLI (not the full engine)
RUN apt-get update && \
    apt-get install -y --no-install-recommends docker-ce-cli docker-compose-plugin

# Create a 'docker' group with the GID passed in as an argument (same as on host); delete the dafault 'docker' group if it exists
RUN echo "Creating docker group with GID ${DOCKER_GID}"
RUN groupdel docker || true
RUN groupadd -g ${DOCKER_GID} docker

# Add the jenkins user to this group
RUN usermod -aG docker jenkins