services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main-slim
    container_name: luna-openwebui
    restart: unless-stopped
    ports:
      - "9707:8080"
    networks:
      - home-lab-net
    volumes:
      - ${DATA_DIR}:/app/backend/data
    env_file:
      - .env
    environment:
      - ENABLE_TOOL_CALLING=${ENABLE_TOOL_CALLING}
      - DEFAULT_FUNCTION_CALLING_MODE=${DEFAULT_FUNCTION_CALLING_MODE}
      - OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENABLE_OLLAMA_API=${ENABLE_OLLAMA_API}
      - DEFAULT_MODELS=${DEFAULT_MODELS}
      - TASK_MODEL_EXTERNAL=${TASK_MODEL_EXTERNAL}
      - ENABLE_AUTOCOMPLETE_GENERATION=${ENABLE_AUTOCOMPLETE_GENERATION}
      - ENABLE_FOLLOW_UP_GENERATION=${ENABLE_FOLLOW_UP_GENERATION}
      - ENABLE_TITLE_GENERATION=${ENABLE_TITLE_GENERATION}
      - ENABLE_BASE_MODELS_CACHE=${ENABLE_BASE_MODELS_CACHE}
      - MODELS_CACHE_TTL=${MODELS_CACHE_TTL}
      - RAG_EMBEDDING_ENGINE=${RAG_EMBEDDING_ENGINE}
      - RAG_OPENAI_API_BASE_URL=${RAG_OPENAI_API_BASE_URL}
      - RAG_OPENAI_API_KEY=${RAG_OPENAI_API_KEY}
      - RAG_EMBEDDING_MODEL=${RAG_EMBEDDING_MODEL}
      - ENABLE_IMAGE_GENERATION=${ENABLE_IMAGE_GENERATION}
      - IMAGE_GENERATION_ENGINE=${IMAGE_GENERATION_ENGINE}
      - IMAGE_GENERATION_MODEL=${IMAGE_GENERATION_MODEL}
      - ENABLE_IMAGE_EDIT=${ENABLE_IMAGE_EDIT}
      - IMAGE_EDIT_MODEL=${IMAGE_EDIT_MODEL}
      - IMAGES_OPENAI_API_BASE_URL=${IMAGES_OPENAI_API_BASE_URL}
      - IMAGES_OPENAI_API_KEY=${IMAGES_OPENAI_API_KEY}
      - IMAGES_EDIT_OPENAI_API_BASE_URL=${IMAGES_EDIT_OPENAI_API_BASE_URL}
      - IMAGES_EDIT_OPENAI_API_KEY=${IMAGES_EDIT_OPENAI_API_KEY}
      - ENABLE_MEMORIES=${ENABLE_MEMORIES}
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@datastore-sql:5432/openwebui
      - VECTOR_DB=${VECTOR_DB}
      - PGVECTOR_DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@datastore-sql:5432/openwebui
      - REDIS_URL=${REDIS_URL}
      - WEBUI_NAME=${WEBUI_NAME}
      - WEBUI_URL=${WEBUI_URL}
      - DEFAULT_LOCALE=${DEFAULT_LOCALE}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - ENABLE_API_KEYS=${ENABLE_API_KEYS}
      - ENABLE_SIGNUP=${ENABLE_SIGNUP}
      - ENABLE_OAUTH_SIGNUP=${ENABLE_OAUTH_SIGNUP}
      - ENABLE_PASSWORD_AUTH=${ENABLE_PASSWORD_AUTH}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OPENID_PROVIDER_URL=${OPENID_PROVIDER_URL}
      - OAUTH_PROVIDER_NAME=${OAUTH_PROVIDER_NAME}
      - OPENID_REDIRECT_URI=${OPENID_REDIRECT_URI}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  home-lab-net:
    external: true
