FROM ghcr.io/open-webui/open-webui:main-slim

COPY static/apple-touch-icon.png /app/build/static/apple-touch-icon.png
COPY static/custom.css /app/build/static/custom.css
COPY static/favicon-96x96.png /app/build/static/favicon-96x96.png
COPY static/favicon-dark.png /app/build/static/favicon-dark.png
COPY static/favicon.ico /app/build/static/favicon.ico
COPY static/favicon.png /app/build/static/favicon.png
COPY static/favicon.svg /app/build/static/favicon.svg
COPY static/logo.png /app/build/static/logo.png
COPY static/site.webmanifest /app/build/static/site.webmanifest
COPY static/splash-dark.png /app/build/static/splash-dark.png
COPY static/splash.png /app/build/static/splash.png
COPY static/web-app-manifest-192x192.png /app/build/static/web-app-manifest-192x192.png
COPY static/web-app-manifest-512x512.png /app/build/static/web-app-manifest-512x512.png

COPY static/apple-touch-icon.png /app/backend/open_webui/static/apple-touch-icon.png
COPY static/custom.css /app/backend/open_webui/static/custom.css
COPY static/favicon-96x96.png /app/backend/open_webui/static/favicon-96x96.png
COPY static/favicon-dark.png /app/backend/open_webui/static/favicon-dark.png
COPY static/favicon.ico /app/backend/open_webui/static/favicon.ico
COPY static/favicon.png /app/backend/open_webui/static/favicon.png
COPY static/favicon.svg /app/backend/open_webui/static/favicon.svg
COPY static/logo.png /app/backend/open_webui/static/logo.png
COPY static/site.webmanifest /app/backend/open_webui/static/site.webmanifest
COPY static/splash-dark.png /app/backend/open_webui/static/splash-dark.png
COPY static/splash.png /app/backend/open_webui/static/splash.png
COPY static/web-app-manifest-192x192.png /app/backend/open_webui/static/web-app-manifest-192x192.png
COPY static/web-app-manifest-512x512.png /app/backend/open_webui/static/web-app-manifest-512x512.png